# Site settings
title: "caiyao blog"
subtitle: "caiyao blog"
description: ""
baseurl: ""
#url: "https://www.altcointrading.net"
url: "http://127.0.0.1:4000"
author: "AltcoinTrading"
markdown: kramdown
## Default image size: 700x360
